import type { Metadata } from "next";
import { Roboto } from "next/font/google";
import "./globals.css";
import { css } from "../../styled-system/css";

const roboto = Roboto({
	variable: "--font-roboto",
	subsets: ["latin"]
});

const html = css({
	fontSize: "62.5%"
});

const body = css({
	fontSize: "1.6rem",
	fontFamily: "var(--font-roboto)"
});

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app"
};

const RootLayout = ({ children }: { children: React.ReactNode }) => {
	return (
		<html lang="en" className={`${html} ${roboto.variable}`}>
			<body className={body}>{children}</body>
		</html>
	);
};

export default RootLayout;
